site_name: Jacob ElasticSearch7 Book
site_description: "Jacob's Elasticsearch7 技术与实战教程"
site_author: "Jacob Xi"
copyright: "Copyright &copy; 2020-9999 Jacob Xi"

plugins:
  - search # necessary for search to work
  - awesome-pages

nav:
  - 'Welcome': "index.md"
  - '一、Elasticsearch 概述':
    - '第一节 ElasticSearch 概述' : 'chap1/1Es_intro.md'
  - '二、Elasticsearch 安装手册':
    - '第一节 Elasticsearch的安装与简单配置' : 'chap2/1ES_vm_install.md'
    - '第二节 Kibana的安装与界面快速预览' : 'chap2/2KB_vm_install.md'
    - '第三节 在Docker容器中运行Elasticsearch Kibana和Cerebro' : 'chap2/3ES_KB_docker.md' 
    - '第四节 Logstash安装与导入数据' : 'chap2/4LogStash_vm_install.md'
  - '三、Elasticsearch 入门查询':
    - '第一节、ElasticSearch 基本概念' : 'chap3/1ES_intro.md'
    - '第二节 文档的基本CRUD与批量操作 & 读取＆Bulk API' : 'chap3/2ES_CRUD.md'
    - '第三节 倒排索引' : 'chap3/3ES_ReverseIndex.md' 
    - '第四节 使用分析器进行分词' : 'chap3/4ES_Analyzer.md'
    - '第五节 ElasticSearch Search语句' : 'chap3/5ES_Search.md'
    - '第六节 ElasticSearch Mapping 介绍' : 'chap3/6ES_Mapping.md'
    - '第七节 Index Template和Dynamic Template' : 'chap3/7ES_Index.md' 
    - '第八节 Elasticsearch Aggregations聚合分析简介' : 'chap3/8ES_Aggr.md'
    - '第九节 Elasticsearch 入门总结 & 测试' : 'chap3/9ES_SUM.md'
  - '四、Elasticsearch 深入搜索':
    - '第一节 基于词项和基于全文的搜索' : 'chap4/1ES_search.md'
    - '第二节 结构化搜索以及搜索的相关性算分' : 'chap4/2ES_search_str_score.md'
    - '第三节 Query & Filtering与多字符串多字段查询' : 'chap4/3ES_query_filter.md' 
    - '第四节 单字符串多字段查询' : 'chap4/4ES_sin_mul_search.md'
    - '第五节 多语言及中文分词与检索' : 'chap4/5ES_multi_lag_ana.md'
    - '第六节 Space Jam，一次全文搜索的实例' : 'chap4/6ES_pra_tmdb.md'
    - '第七节 使⽤用 Search Template 和 Index Alias' : 'chap4/7ES_ST_IA.md' 
    - '第八节 综合排序:Function Score Query 优化算分' : 'chap4/8ES_FUNC_SCORE.md'
    - '第九节 Term & Phrase Suggester' : 'chap4/9ES_suggester.md'
    - '第十节 ⾃动补全与基于上下文的提示' : 'chap4/10ES_Autocomplete.md'
    - '第十一节 跨集群搜索' : 'chap4/11ES_CrossSearch.md'
  - '五、分布式特性及分布式搜索的机制':
    - '第一节 集群分布式模型及选主与脑裂问题' : 'chap5/1ES_cluster.md'
    - '第二节 分⽚与集群的故障转移' : 'chap5/2ES_shard.md'
    - '第三节 ⽂档分布式存储' : 'chap5/3ES_doc_shard.md'
    - '第四节 分⽚及其生命周期' : 'chap5/4ES_shared_lifecycle.md'
    - '第五节 剖析分布式查询及相关性算分' : 'chap5/5ES_SE_Score.md'
    - '第六节 排序及Doc Values&Fielddata' : 'chap5/6ES_Sort_query.md'
    - '第七节 分页与遍历 – From，Size，Search After & Scroll API' : 'chap5/7ES_Pages_Traverse.md'
    - '第八节 处理并发读写操作' : 'chap5/8ES_Concurrent_process.md'
  - '六、深入聚合分析':
    - '第一节 Bucket & Metric 聚合分析及嵌套聚合' : 'chap6/1chap6_bucket_metrics.md'
    - '第二节 Pipeline 聚合分析' : 'chap6/2chap6_pipeline_metrics.md'
    - '第三节 聚合的作⽤范围及排序' : 'chap6/3chap6_aggragate_scope_order.md'
    - '第四节 聚合的精准度问题' : 'chap6/4chap6_accurate_aggragate.md'
  - '七、数据建模':
    - '第一节 对象及 Nested 对象' : 'chap7/1chap7_nested_obj.md'
    - '第二节 文档的父子关系' : 'chap7/2chap7_parent_child.md'
    - '第三节 Update By Query & Reindex API' : 'chap7/3chap7_updateindex_reindex.md'
    - '第四节 Ingest Pipeline 与 Painless Script' : 'chap7/4chap7_ingest_painless.md'
    - '第五节 Elasticsearch 数据建模实例' : 'chap7/5chap7_es_model.md'
    - '第六节 Elasticsearch 数据建模最佳实践' : 'chap7/6chap7_es_model_pra.md'
    - '第七节 第二部分总结回顾' : 'chap7/7chap7_es_sum2.md'
  - '八、数据保护':
    - '第一节 集群身份认证与用户鉴权' : 'chap8/1ES_cluster_IAM.md'
    - '第二节 集群内部间的安全通信' : 'chap8/2ES_cluster_enc_transit.md'
    - '第三节 集群与外部间的安全通信' : 'chap8/3ES_cluster_out_sec.md'
  - '九、水平扩展Elasticsearch集群':
    - '第一节 常见的集群部署方式' : 'chap9/1ES_cluster_deploy.md'
    - '第二节 Hot & Warm 架构与 Shard Filtering' : 'chap9/2ES_hot_warm.md'
    - '第三节 分片设定及管理' : 'chap9/3ES_shard_settings.md'
    - '第四节 如何对集群进行容量规划' : 'chap9/4ES_cluster_plan.md'
    - '第五节 云上管理 Elasticsearch 的一些方法' : 'chap9/5ES_Cloud.md'
  - '十、使用 Kubernets 安装 EFK 集群':
    - '第一节 kubernetes 日志架构' : 'chap10/1log_architecture.md'
    - '第二节 在 K8S 上搭建 EFK 日志收集系统' : 'chap10/2EFK_log.md'
    - '第三节 在 Kubernetes 安装 EFK 日志收集系统[更新]' : 'chap10/16EFK_log_adv.md'
    - '第四节 EFK kibana 日志分析' : 'chap10/17EFK_log_Ana.md'
    - '第五节 基于EKF日志的报警' : 'chap10/18EFK_log_alert.md'
    - '第六节 使用Operator快速部署Elasticsearch集群' : 'chap10/3ECK_operator.md'


repo_url: https://github.com/Chao-Xi/jxes7book.git
repo_name: "jxes7book"

theme: 
  language: zh
  name: 'material'
  include_sidebar: true
  logo: 'images/logo.png'
  favicon: 'images/logo.png'
  feature:
    tabs: false
  palette:
    primary: 'blue'
    accent: 'blue'
  i18n:
    prev: 'Previous'
    next: 'Next'